name: Business Central AL CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Business Central Development Environment
        uses: microsoft/navcontainerhelper@main
        with:
          containerName: 'bcdev'
          artifactUrl: 'https://bc.sandbox.url'
          licenseFile: ${{ secrets.BC_LICENSE }}

      - name: Compile AL Project
        run: |
          Import-Module BCContainerHelper
          New-BcContainer -accept_eula -containerName "BCContainer" -artifactUrl "https://bc.sandbox.url"
          Compile-BcContainerApp -containerName "BCContainer" -appProjectFolder "$env:GITHUB_WORKSPACE" -appOutputFile "Output.app"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: business-central-app
          path: Output.app

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: business-central-app
          path: .

      - name: Run Business Central Tests
        run: |
          # Here, add commands to run AL test automation (requires BC Test Toolkit)

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: business-central-app
          path: .

      - name: Deploy to Business Central Sandbox
        run: |
          Publish-BcContainerApp -containerName "BCContainer" -appFile "Output.app"
