name: Business Central AL CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AL Compiler
        run: |
          Write-Host "Using AL Compiler from Business Central Development Environment"
        shell: pwsh

      - name: Compile AL Project
        run: |
          $ALCompilerPath = "C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\190\AL Development Environment\alc.exe"
          $AppSource = "$env:GITHUB_WORKSPACE\src\app.json"
          $AppOutput = "$env:GITHUB_WORKSPACE\Output.app"

          if (!(Test-Path $ALCompilerPath)) {
            Write-Error "AL Compiler (alc.exe) not found at expected location: $ALCompilerPath"
            exit 1
          }

          & $ALCompilerPath /project:$env:GITHUB_WORKSPACE /packagecachepath:$env:GITHUB_WORKSPACE\.alpackages /out:$AppOutput

          if (!(Test-Path $AppOutput)) {
            Write-Error "Compilation failed! Output.app was not generated."
            exit 1
          } else {
            Write-Host "Compilation successful. Output.app created at $AppOutput"
          }
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: business-central-app
          path: Output.app

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: business-central-app
          path: .

      - name: Run Business Central Tests
        run: |
          Import-Module BcContainerHelper
          Invoke-BCAppTests -tenant "default" -userName "${{ secrets.BC_USERNAME }}" -password (ConvertTo-SecureString "${{ secrets.BC_PASSWORD }}" -AsPlainText -Force) -serverInstance "BCServerInstance" -testSuite "Default"
        shell: pwsh

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: business-central-app
          path: .

      - name: Deploy to Business Central
        run: |
          Import-Module BcContainerHelper
          Publish-BCApp -tenant "default" -userName "${{ secrets.BC_USERNAME }}" -password (ConvertTo-SecureString "${{ secrets.BC_PASSWORD }}" -AsPlainText -Force) -serverInstance "BCServerInstance" -appFile "Output.app"
        shell: pwsh
