name: Business Central AL CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AL Compiler
        run: |
          Invoke-WebRequest -Uri "https://businesscentral.dynamics.com/ALCompiler.zip" -OutFile "ALCompiler.zip"
          Expand-Archive -Path "ALCompiler.zip" -DestinationPath "ALCompiler"

      - name: Compile AL Project
        run: |
          ALCompiler\alc.exe /project:. /out:Output.app /packagecachepath:"./.alpackages"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: business-central-app
          path: Output.app

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: business-central-app
          path: .

      - name: Run Business Central Tests
        run: |
          # Here, add commands to run AL test automation (requires BC Test Toolkit)

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: business-central-app
          path: .

      - name: Deploy to Business Central Sandbox
        run: |
          # Example: Use BCContainerHelper to deploy the extension
          Import-Module BCContainerHelper
          New-BcContainer -accept_eula -containerName "BCContainer" -artifactUrl "https://bc.sandbox.url"
          Publish-BcContainerApp -containerName "BCContainer" -appFile "Output.app"
